# lumie/scale/scalar_scale_impl.py
from typing import Any, Protocol, TypeVar

from ._core import ComparisonResult

R = TypeVar('R')
T = TypeVar('T')


class ScalarScaleImpl(Protocol[R]):
    def to_repr(self, value: object) -> R: ...

    def shape(self, value: R) -> tuple[int, ...] | None: ...

    # implementation should raise UnsupportedScaleError if the conversion is not supported
    def as_(self, value: R, number_type: type[T]) -> T: ...

    def abs(self, value: R) -> R: ...
    def neg(self, value: R) -> R: ...
    def add(self, lhs: R, rhs: R) -> R: ...
    def sub(self, lhs: R, rhs: R) -> R: ...
    def mul(self, lhs: R, rhs: R) -> R: ...

    def invalid_value(self) -> R: ...  # nan のような値を返すことを想定している

    # ポリシーによってZeroDivisionErrorを投げる/ nan のような値を返す のようなスイッチができていいかもしれない。
    def div(self, lhs: R, rhs: R) -> R: ...

    def is_zero(self, value: R) -> bool: ...

    # スカラー状の(shape が Noneの)スケールに対して適用されることを想定している。
    def compare(self, lhs: R, rhs: R) -> ComparisonResult: ...

    # オペランドのいずれかがテンソル状の(shape が None でない)スケールの場合に対して適用され。
    # ブロードキャストされたshapeの0,1,2,3(ComparisonResultの値)からなるテンソルを返すことを想定している。
    def elementwise_compare(self, lhs: R, rhs: R) -> Any: ...  # noqa: ANN401

    # should return the same hash value for values that are considered equal by compare()
    def hash(self, value: R) -> int: ...

    # __str__の実装に使用される。値の詳細な情報を含まなくてよい。
    def format_value(self, value: R) -> str: ...
    # __repr__の実装に使用される。値の詳細な情報を含むべき。
    def format_value_detailed(self, value: R) -> str: ...
